// --- Enums ---
export enum PurchaseOrderStatus {
  DRAFT = "DRAFT",
  DRAFT_CANCELLED = "DRAFT_CANCELLED",
  CONFIRMED = "CONFIRMED",
  ORDER_CANCELLED = "ORDER_CANCELLED",
  PARTIALLY_FULFILLED = "PARTIALLY_FULFILLED",
  FULLY_DELIVERED = "FULLY_DELIVERED",
  PARTIALLY_FULFILLED_CLOSED = "PARTIALLY_FULFILLED_CLOSED",
}

export enum LineItemStatus {
  DRAFT = "DRAFT",
  CONFIRMED = "CONFIRMED",
  LINE_CANCELLED = "LINE_CANCELLED",
  PARTIALLY_FULFILLED = "PARTIALLY_FULFILLED",
  FULLY_DELIVERED = "FULLY_DELIVERED",
}
